// UG Level 100 course catalog — used to power the course-code suggestions.
// Source: University of Ghana Comprehensive Level 100 Course Catalog.
const UG_COURSES = [
  // University Required Courses
  { code: "UGRC 110", title: "Academic Writing I" },
  { code: "UGRC 120", title: "Numeracy Skills" },
  { code: "UGRC 131", title: "Understanding Human Societies: Culture and Development" },
  { code: "UGRC 132", title: "Understanding Human Societies: Religion and Societies" },
  { code: "UGRC 133", title: "Understanding Human Societies: Economy and Business" },
  { code: "UGRC 134", title: "Understanding Human Societies: Language in Society" },
  { code: "UGRC 135", title: "Understanding Human Societies: Health and Safety in our Lives" },
  { code: "UGRC 136", title: "Understanding Human Societies: Governance in the Information Society" },
  { code: "UGRC 141", title: "Science and Technology in our Lives: Everyday Chemistry" },
  { code: "UGRC 142", title: "Science and Technology in our Lives: Animals in our Lives" },
  { code: "UGRC 143", title: "Science and Technology in our Lives: Everyday Physics" },
  { code: "UGRC 144", title: "Science and Technology in our Lives: Geohazards" },
  { code: "UGRC 145", title: "Science and Technology in our Lives: Food and Nutrition in Everyday Life" },
  { code: "UGRC 146", title: "Science and Technology in our Lives: Earth Resources" },
  { code: "UGRC 150", title: "Critical Thinking and Practical Reasoning" },
  { code: "UGRC 160", title: "Introduction to Literature" },
  { code: "UGRC 170", title: "General Mathematics" },

  // UGBS / Law / Humanities
  { code: "UGBS 101", title: "Introduction to Business Administration" },
  { code: "UGBS 102", title: "Introduction to Computing in Business" },
  { code: "UGBS 104", title: "Principles of Management" },
  { code: "UGBS 105", title: "Introduction to Public Administration" },
  { code: "UGBS 107", title: "Quantitative Methods for Business" },
  { code: "ACCT 101", title: "Introduction to Financial Accounting I" },
  { code: "ACCT 102", title: "Introduction to Financial Accounting II" },
  { code: "FLAW 101", title: "The Ghana Legal System" },
  { code: "FLAW 102", title: "Legal Method" },
  { code: "FLAW 103", title: "Law of Contract I" },
  { code: "FLAW 105", title: "Constitutional Law I" },
  { code: "FLAW 107", title: "Criminal Law I" },
  { code: "ECON 101", title: "Introduction to Economics I (Microeconomics)" },
  { code: "ECON 102", title: "Introduction to Economics II (Macroeconomics)" },
  { code: "POLI 111", title: "Introduction to the Study of Political Science" },
  { code: "POLI 112", title: "Political Institutions" },
  { code: "SOCI 121", title: "Principles of Social Organization" },
  { code: "SOCI 122", title: "Diversity of Peoples and Cultures" },
  { code: "PSYC 101", title: "Elements of Psychology" },
  { code: "PSYC 102", title: "Psychology for Everyday Living" },
  { code: "GEOG 111", title: "Introduction to Physical Geography" },
  { code: "GEOG 112", title: "Introduction to Human Geography" },
  { code: "SOWK 111", title: "Development and Social Services" },
  { code: "SOWK 112", title: "Philosophy and Practice of Social Work" },
  { code: "HIST 111", title: "Earliest Civilizations" },
  { code: "ARCH 111", title: "Approaches to the Study of the Past" },
  { code: "PHIL 101", title: "Introduction to Philosophy" },
  { code: "SREL 111", title: "Introduction to Islamic / Judeo-Christian Studies" },
  { code: "ENGL 111", title: "Foundation English I" },

  // CBAS — Computer Science, Maths, Sciences
  { code: "DCIT 101", title: "Introduction to Computer Science I" },
  { code: "DCIT 102", title: "Introduction to Computer Science II" },
  { code: "DCIT 103", title: "Office Productivity Tools" },
  { code: "DCIT 104", title: "Programming / Program Design" },
  { code: "MATH 121", title: "Algebra and Trigonometry" },
  { code: "MATH 122", title: "Calculus I" },
  { code: "MATH 123", title: "Algebra and Geometry" },
  { code: "MATH 126", title: "Calculus II" },
  { code: "STAT 111", title: "Introduction to Statistics and Probability I" },
  { code: "STAT 112", title: "Introduction to Statistics and Probability II" },
  { code: "CHEM 111", title: "General Chemistry I" },
  { code: "CHEM 112", title: "General Chemistry II" },
  { code: "CHEM 113", title: "Foundation Chemistry I" },
  { code: "CHEM 120", title: "General Chemistry Practical" },
  { code: "PHYS 105", title: "Practical Physics I" },
  { code: "PHYS 143", title: "Mechanics and Thermal Physics" },
  { code: "PHYS 144", title: "Electricity and Magnetism" },
  { code: "EASC 101", title: "Physical Geology" },
  { code: "BIOL 111", title: "Introductory Cell Biology and Genetics" },
  { code: "BIOL 112", title: "Plant and Animal Diversity" },
  { code: "FAEN 101", title: "Algebra for Engineers" },
  { code: "FAEN 102", title: "Calculus for Engineers" },
  { code: "AGRC 101", title: "General Agriculture" },
  { code: "AGRC 102", title: "Introduction to Animal and Crop Science" },

  // Health Sciences & Education
  { code: "NURS 111", title: "Introduction to Nursing" },
  { code: "NURS 112", title: "Anatomy and Physiology for Nurses I" },
  { code: "PHAR 111", title: "Introduction to Pharmacy" },
  { code: "VETM 101", title: "Introduction to Veterinary Medicine I" },
  { code: "EDTE 101", title: "Introduction to Education and Teaching" },
  { code: "EDTE 102", title: "Philosophical Foundations of Education" },
  { code: "INFS 111", title: "Information in Society" },
  { code: "INFS 112", title: "Introduction to Information Management" },
];

// Sample schedule used for the "Load a sample" demo button.
// Deliberately generic (not tied to any one student) and includes one
// overlap so first-time visitors immediately see the clash detector work.
const SAMPLE_SCHEDULE = [
  { code: "DCIT 104", group: "Group 2", day: "MON", start: "17:30", end: "19:20", venue: "JQB 22" },
  { code: "MATH 122", group: "Group 3", day: "MON", start: "09:30", end: "11:30", venue: "STAT 002" },
  { code: "MATH 126", group: "Group 1", day: "TUE", start: "08:30", end: "10:20", venue: "STAT 002" },
  { code: "STAT 112", group: "Group GK-D", day: "TUE", start: "17:30", end: "19:20", venue: "STAT 002" },
  { code: "UGRC 110", group: "Group 19", day: "WED", start: "09:30", end: "11:20", venue: "TBD" },
  { code: "DCIT 102", group: "Group 1", day: "WED", start: "15:30", end: "17:20", venue: "NNB 2" },
  // Intentional clash for the demo: two sessions overlap Wednesday morning.
  { code: "STAT 111", group: "Group A", day: "WED", start: "10:30", end: "12:00", venue: "STAT 004" },
];
